---
- name: Start of Jinja2 Template Push
  hosts: servers
  vars:
  gather_facts: True
  become: False
  tasks:

    - name: Copy template over to all hosts
      template:
        src: /root/template.j2
        dest: "/root/template.txt"

