---
- name: Start of Jinja2 Template Push
  hosts: servers
  vars:
  gather_facts: True
  become: False
  tasks:

    - name: Get information for uptime on all systems
      shell: uptime
      register: uptime

    - name: Report out to just main server
      template:
        src: /root/template.j2
        dest: "/root/report.{{ansible_date_time.iso8601_basic_short}}.txt"
      run_once: yes
      delegate_to: localhost

